<?php
require_once "db_config.php";

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}

// Require login
if (!isset($_SESSION['loggedin']) || $_SESSION['loggedin'] !== true) {
    header('Location: login.php');
    exit;
}

$role = peachtrack_effective_role();
$empId = peachtrack_effective_employee_id();
$name = peachtrack_effective_name();

// Range presets for simple "numbers only" print
$range = $_GET['range'] ?? 'week';
$today = date('Y-m-d');

if ($range === 'day') {
    $from = $today; $to = $today;
} elseif ($range === 'month') {
    $from = date('Y-m-01'); $to = $today;
} else {
    // week default
    $range = 'week';
    $from = date('Y-m-d', strtotime('-6 days'));
    $to = $today;
}

// Employee-only summary (admin viewing as employee is allowed)
if ($role !== '102') {
    header('Location: index.php');
    exit;
}

$hasIsDeleted = peachtrack_has_column($conn, 'tip', 'Is_Deleted');
$tipJoinCond = $hasIsDeleted ? " AND (t.Is_Deleted IS NULL OR t.Is_Deleted = 0)" : "";

$hasTipSale = peachtrack_has_column($conn, 'tip', 'Sale_Amount');
$salesExpr = $hasTipSale ? 'COALESCE(SUM(t.Sale_Amount),0)' : 'COALESCE(SUM(s.Sale_Amount),0)';

$sql = "
SELECT
  COUNT(DISTINCT s.Shift_ID) AS shifts,
  COALESCE(SUM(t.Tip_Amount),0) AS tips,
  COALESCE(SUM(CASE WHEN t.Is_It_Cash=1 THEN t.Tip_Amount ELSE 0 END),0) AS cash,
  COALESCE(SUM(CASE WHEN t.Is_It_Cash=0 THEN t.Tip_Amount ELSE 0 END),0) AS elec,
  {$salesExpr} AS sales
FROM shift s
LEFT JOIN tip t ON t.Shift_ID = s.Shift_ID{$tipJoinCond}
WHERE s.Employee_ID = ?
  AND DATE(s.Start_Time) BETWEEN ? AND ?;
";

$stmt = $conn->prepare($sql);
$stmt->bind_param('iss', $empId, $from, $to);
$stmt->execute();
$sum = $stmt->get_result()->fetch_assoc() ?: ['shifts'=>0,'tips'=>0,'cash'=>0,'elec'=>0,'sales'=>0];

?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PeachTrack — Tip Summary</title>
  <link rel="stylesheet" href="style.css" />
  <style>
    body{ background:#fff; }
    .wrap{ max-width:820px; margin:40px auto; padding:0 18px; }
    .summary{ border:1px solid rgba(17,24,39,.10); border-radius:16px; padding:18px; }
    .grid{ display:grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap:12px; }
    .k{ border:1px solid rgba(17,24,39,.10); border-radius:14px; padding:14px; }
    .k .label{ font-size:12px; color:rgba(17,24,39,.65); font-weight:800; text-transform:uppercase; letter-spacing:.06em; }
    .k .value{ font-size:28px; font-weight:900; margin-top:6px; }
    .muted{ color:rgba(17,24,39,.65); }
    @media print{
      .no-print{ display:none !important; }
      .wrap{ margin:0; }
    }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="no-print" style="display:flex; justify-content:space-between; align-items:center; gap:10px; margin-bottom:16px;">
      <a class="btn btn-ghost" href="index.php" style="text-decoration:none;">← Back</a>
      <button class="btn btn-primary" onclick="window.print()">Print</button>
    </div>

    <h1 style="margin:0 0 6px;">Tip Summary</h1>
    <div class="muted" style="margin-bottom:16px;">Employee: <strong><?php echo htmlspecialchars($name); ?></strong> • Range: <strong><?php echo htmlspecialchars($from); ?> → <?php echo htmlspecialchars($to); ?></strong></div>

    <div class="summary">
      <div class="grid">
        <div class="k"><div class="label">Shifts</div><div class="value"><?php echo (int)$sum['shifts']; ?></div></div>
        <div class="k"><div class="label">Total Tips</div><div class="value">$<?php echo htmlspecialchars(number_format((float)$sum['tips'],2)); ?></div></div>
        <div class="k"><div class="label">Cash Tips</div><div class="value">$<?php echo htmlspecialchars(number_format((float)$sum['cash'],2)); ?></div></div>
        <div class="k"><div class="label">Electronic Tips</div><div class="value">$<?php echo htmlspecialchars(number_format((float)$sum['elec'],2)); ?></div></div>
        <div class="k" style="grid-column:1 / -1;"><div class="label">Sales (range)</div><div class="value">$<?php echo htmlspecialchars(number_format((float)$sum['sales'],2)); ?></div>
          <?php if (!peachtrack_has_column($conn,'tip','Sale_Amount')): ?>
            <div class="muted" style="font-size:12px; margin-top:6px;">Note: individual sale amounts per tip are not enabled yet (tip.Sale_Amount missing). Sales shown here are shift totals.</div>
          <?php endif; ?>
        </div>
      </div>
    </div>

    <div class="muted" style="margin-top:14px; font-size:12px;">Generated by PeachTrack • © 2026 Cyber Dominion</div>
  </div>
</body>
</html>
